import type { Metadata } from 'next';
import { Montserrat } from "next/font/google"
import './globals.css';

const montserrt = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
})

export const metadata: Metadata = {
  title: 'Skypro-music',
  description: 'Generated by skypro-music',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrt.variable}`}>
        {children}
      </body>
    </html>
  );
}
